```
$ curl -L -o ~/Downloads/linkedin-job-2023.zip https://www.kaggle.com/api/v1/datasets/download/rajatraj0502/linkedin-job-2023
$ unzip -l linkedin-job-2023.zip
Archive:  linkedin-job-2023.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   381021  2023-09-03 18:34   benefits.csv
  5887484  2023-09-03 18:34   companies.csv
   439563  2023-09-03 18:34   company_industries.csv
  3071450  2023-09-03 18:34   company_specialities.csv
   490871  2023-09-03 18:34   employee_counts.csv
   309470  2023-09-03 18:34   job_industries.csv
 64179960  2023-09-03 18:34   job_postings.csv
   427891  2023-09-03 18:34   job_skills.csv
---------                     -------
 75187710                     8 files
```

In [3]:
print('hello world')

hello world

In [4]:
import zipfile
import pandas as pd

In [5]:
with zipfile.ZipFile('../linkedin-job-2023.zip') as z:
  with z.open("companies.csv") as f:
        df_companies = pd.read_csv(f)
  with z.open("job_postings.csv") as f:
        df_job_postings = pd.read_csv(f)

df_companies.shape, df_job_postings.shape

((6063, 10), (15886, 27))

In [6]:
df_job_postings

,job_id,company_id,title,description,max_salary,med_salary,min_salary,pay_period,formatted_work_type,location,...,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type
0,85008768,NaN,Licensed Insurance Agent,While many industries were hurt by the last fe...,52000.0,NaN,45760.0,YEARLY,Full-time,"Chico, CA",...,1.710000e+12,NaN,NaN,NaN,1.690000e+12,NaN,1,FULL_TIME,USD,BASE_SALARY
1,133114754,77766802.0,Sales Manager,Are you a dynamic and creative marketing profe...,NaN,NaN,NaN,NaN,Full-time,"Santa Clarita, CA",...,1.700000e+12,NaN,NaN,NaN,1.690000e+12,NaN,0,FULL_TIME,NaN,NaN
2,133196985,1089558.0,Model Risk Auditor,Join Us as a Model Risk Auditor – Showcase You...,NaN,NaN,NaN,NaN,Contract,"New York, NY",...,1.700000e+12,NaN,NaN,NaN,1.690000e+12,NaN,0,CONTRACT,NaN,NaN
3,381055942,96654609.0,Business Manager,Business ManagerFirst Baptist Church ForneyFor...,NaN,NaN,NaN,NaN,Full-time,"Forney, TX",...,1.700000e+12,NaN,NaN,NaN,1.690000e+12,NaN,0,FULL_TIME,NaN,NaN
4,529257371,1244539.0,NY Studio Assistant,YOU COULD BE ONE OF THE MAGIC MAKERS\nKen Fulk...,NaN,NaN,NaN,NaN,Full-time,"New York, NY",...,1.710000e+12,NaN,NaN,NaN,1.690000e+12,NaN,1,FULL_TIME,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15881,3701373516,74718032.0,Sanitation Technician,"Location:\n\nWest Columbia, SC, US, 29172\n\n2...",NaN,NaN,NaN,NaN,Part-time,"West Columbia, SC",...,1.700000e+12,NaN,Entry level,NaN,1.690000e+12,aspirebakeriescareers.com,0,PART_TIME,NaN,NaN
15882,3701373522,38897.0,Unit Secretary,Job Title: Unit Secretary\nDepartment: Nursing...,NaN,NaN,NaN,NaN,Full-time,"Teaneck, NJ",...,1.700000e+12,NaN,Entry level,NaN,1.690000e+12,recruiting.ultipro.com,0,FULL_TIME,NaN,NaN
15883,3701373523,38897.0,"Radiology Aide, Perdiem","Job Title: Radiology Aide, Perdiem\nDepartment...",NaN,NaN,NaN,NaN,Part-time,"Teaneck, NJ",...,1.700000e+12,NaN,Entry level,NaN,1.690000e+12,recruiting.ultipro.com,0,PART_TIME,NaN,NaN
15884,3701373524,2623.0,MRI Manager,Grade 105\nJob Type: Officer of Administration...,135000.0,NaN,110000.0,YEARLY,Full-time,"New York, NY",...,1.700000e+12,NaN,Mid-Senior level,NaN,1.690000e+12,opportunities.columbia.edu,0,FULL_TIME,USD,BASE_SALARY
15885,3701373527,84659.0,Area Director of Business Development,Nexion Health Management affiliates operate 56...,NaN,NaN,NaN,NaN,Full-time,"Vicksburg, MS",...,1.700000e+12,NaN,NaN,NaN,1.690000e+12,NaN,0,FULL_TIME,NaN,NaN

In [7]:
df_companies

,company_id,name,description,company_size,state,country,city,zip_code,address,url
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm
1,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare
2,1021,GE Power,"GE Power, part of GE Vernova, is a world energ...",7.0,NY,US,Schenectady,12345,1 River Road,https://www.linkedin.com/company/gepower
3,1025,Hewlett Packard Enterprise,Official LinkedIn of Hewlett Packard Enterpris...,7.0,Texas,US,Houston,77389,1701 E Mossy Oaks Rd Spring,https://www.linkedin.com/company/hewlett-packa...
4,1028,Oracle,We’re a cloud technology company that provides...,7.0,Texas,US,Austin,78741,2300 Oracle Way,https://www.linkedin.com/company/oracle
...,...,...,...,...,...,...,...,...,...,...
6058,3700144594,BYREDO,"""Beauty can be many things to many people. Our...",3.0,0,0,0,0,0,https://www.linkedin.com/company/byredo
6059,3700144710,"Pros2Plan, a division of Spinnaker SCA","Pros2Plan, a division of Spinnaker Services L...",2.0,CO,US,Boulder,80303,0,https://www.linkedin.com/company/pros2plan
6060,3700147810,Ascendo Resources,Ascendo Resources is a certified minority owne...,3.0,FL,US,Coral Gables,33134,2 Alhambra Plaza,https://www.linkedin.com/company/ascendoresources
6061,3700150295,The Crox Group,"The Crox Group, Head Quartered in Chicago, wit...",2.0,Illinois,US,Lincolnwood,60712,6818 N Lincoln Ave,https://www.linkedin.com/company/the-crox-group
6062,3700152513,Sidley Austin LLP,Sidley is an elite global law firm with nearly...,5.0,Illinois,US,Chicago,60603,One South Dearborn,https://www.linkedin.com/company/sidley-austin

In [8]:
print(df_job_postings.columns)
print(df_companies.columns)

Index(['job_id', 'company_id', 'title', 'description', 'max_salary',
       'med_salary', 'min_salary', 'pay_period', 'formatted_work_type',
       'location', 'applies', 'original_listed_time', 'remote_allowed',
       'views', 'job_posting_url', 'application_url', 'application_type',
       'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc',
       'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type'],
      dtype='str')
Index(['company_id', 'name', 'description', 'company_size', 'state', 'country',
       'city', 'zip_code', 'address', 'url'],
      dtype='str')

In [9]:
job_cols = ["job_id", "company_id", "title", "description"]
company_cols = ["company_id", "name",] # "description"]

In [10]:
df = df_job_postings[job_cols].merge(df_companies[company_cols], on="company_id", how="left")
df_cols = ["job_id", "title", "description", "name"]
df = df[df_cols].rename(columns={"name": "company_name"})
df.shape, df.columns

((15886, 4),
 Index(['job_id', 'title', 'description', 'company_name'], dtype='str'))

In [15]:
df.head()

,job_id,title,description,company_name
0,85008768,Licensed Insurance Agent,While many industries were hurt by the last fe...,NaN
1,133114754,Sales Manager,Are you a dynamic and creative marketing profe...,CargoLogin.
2,133196985,Model Risk Auditor,Join Us as a Model Risk Auditor – Showcase You...,Employvision Inc.
3,381055942,Business Manager,Business ManagerFirst Baptist Church ForneyFor...,First Baptist Church Forney
4,529257371,NY Studio Assistant,YOU COULD BE ONE OF THE MAGIC MAKERS\nKen Fulk...,Ken Fulk Inc

In [16]:
df[:200].to_csv("../job_postings.csv")